### ISSUE TITLE
501 5.1.7 Bad address mailbox syntax.

### ISSUE THREAD

**Issue by vault-thirteen** [valord577/mailx#1]
I get the following error when I try to send a message using the Yandex SMTP server:
> 501 5.1.7 Bad address mailbox syntax.

It looks like the "From" header is not set in your library. 
Am I right ?

**Comment by vault-thirteen** [comment]
It looks like, Yandex SMTP server requires a username to end with the @ followed with the domain name. So, this is not a bug.

**Comment by fro-oo** [comment]
Hi @vault-thirteen 
We can't send any email using Yandex address because the From is not set in the Headers.
How do you manage to make it possible?

**Comment by vault-thirteen** [comment]
Hello there, @fro-oo .
Do you mean how technically or how in general ?

Technically, I am using your library.

```go
func (m *Mailer) SendMail(
	recipients []string,
	subject string,
	message string,
) (err error) {
	msg := mailx.NewMessage()
	msg.SetTo(recipients...)
	msg.SetSubject(subject)
	msg.SetPlainBody(message)
	msg.SetUserAgent(m.userAgent)

	dialer := mailx.Dialer{
		Host:         m.host,
		Port:         int(m.port),
		Username:     m.username,
		Password:     m.pwd,
		SSLOnConnect: true,
	}

	err = dialer.DialAndSend(msg)
	if err != nil {
		return err
	}

	return nil
}
```

If in general, then it is still a mystery to me. I have had troubles with the Yandex SMTP server for several days. They were blocking all my test messages for some strange reason. But then suddenly they stopped blocking messages without a reason. It is still a mystery to me how Yandex checks this aspect.

**Comment by fro-oo** [comment]
Well @vault-thirteen 

We have find out that "From" is needed by Yandex in the header.
Your setFrom wasn't working.

In our fork we have removed `func (m *Message) setFrom(from string)` from `msg.go` and reapplied the func to `msg_export.go` but make it global: `func (m *Message) SetFrom(from string)`.

Then changed in `sender.go` `m.setFrom(s.from)` to `m.SetFrom(s.from)`.

**Comment by valord577** [comment]
@fro-oo PR please?

**Comment by fro-oo** [comment]
Sorry @valord577 
I was off :-D
Thx for the fix 👏
